name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar à VM e fazer deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/memoro-app/memoro-app-laravel

            php artisan down

            git pull origin main

            composer install --no-dev --optimize-autoloader

            php artisan migrate
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear

            sudo systemctl restart apache2

            php artisan up
