name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar à VM e fazer deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/memoro-app/memoro-app-laravel

            sudo -u www-data php artisan down

            sudo -u www-data git pull origin main

            csudo -u www-data composer install --no-dev --optimize-autoloader

            sudo -u www-data php artisan migrate
            sudo -u www-data php artisan cache:clear
            sudo -u www-data php artisan config:clear
            sudo -u www-data php artisan route:clear
            sudo -u www-data php artisan view:clear

            sudo systemctl restart apache2

            sudo -u www-data php artisan up
